language: python

python:
  - "3.6"

services:
  - postgresql

env:
  global:
    - APP_SETTINGS = testing

install:
  - "pip install -r requirements.txt"

before_script:
  - "psql -c 'create ' - U postgres"
script:
  - python3 -m pytest --cov=app/

after_success:
  - coveralls 