language: python

python:
  - "3.6"

services:
  - postgresql

env:
  global:
    - APP_SETTINGS = test_env

install:
  - "pip install -r requirements.txt"

before_script:
  - "psql -c 'create database test_iReporter_db;' -U postgres"
script:
  - pytest --cov

after_success:
  - coveralls 